host: your-domain.example.com
listen: ':443'
root: ./public
ssl:
  autoCert:
    enable: true
log:
  output: stderr

handlers:
  'static':
    type: fs
    indexNames: [index.html]

routes:
  - path: /
    handler: static
