name: Go

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - 
        name: Check gofmt
        run: diff -u <(echo -n) <(gofmt -d .)
      - 
        name: Run golangci-lint
        run: | # https://github.com/golangci/golangci-lint/issues/2649
          export PATH=$PATH:$(go env GOPATH)/bin
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2
          golangci-lint run
      -
        name: Tests
        run: |
          go mod tidy
          go test -v ./...
